# Default configuration for the theme
# These values will be overridden by the site's configuration

[params]
# Default sidebar modules
sidebarModules = ["search", "newsletter", "categories", "tags", "popular", "recent", "archives"]
sidebarPosition = "right"

# Enable features
enableSearch = true
showReadingTime = true
showHeroSection = true
dateFormat = "January 2, 2006"
recentPostsCount = 5

[params.author]
name = ""
bio = ""
avatar = ""
email = ""

[params.social]
twitter = ""
github = ""
linkedin = ""

[params.advertisement]
enabled = false