name = "hugo-bootstrap-blog"
license = "MIT"
licenselink = "https://github.com/ngs/hugo-bootstrap-blog/blob/main/LICENSE.md"
description = "A clean, responsive Hugo theme for blogging with Bootstrap 5.3, featuring modular sidebar, dark mode, and i18n support"
homepage = "https://github.com/ngs/hugo-bootstrap-blog"
demosite = "https://hugo-bootstrap-blog.netlify.app"
tags = ["blog", "bootstrap", "responsive", "dark-mode", "sidebar", "minimal", "clean", "modern", "seo", "fast"]
features = ["blog", "responsive", "dark mode", "modular sidebar", "i18n", "seo", "bootstrap5", "search"]
min_version = "0.120.0"

[author]
  name = "Atsushi Nagase"
  homepage = "https://ngs.io"

[original]
  name = "Bootstrap Blog"
  homepage = "https://github.com/ngs/hugo-bootstrap-blog"
  repo = "https://github.com/ngs/hugo-bootstrap-blog"